-- MySQL Script generated by MySQL Workbench
-- 01/24/15 11:55:03
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mybdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horario` ;

CREATE TABLE IF NOT EXISTS `horario` (
  `idhorario` INT(11) NOT NULL,
  `horaEntrada` TIME NULL DEFAULT NULL,
  `horaSalida` TIME NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idhorario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asistencia` ;

CREATE TABLE IF NOT EXISTS `asistencia` (
  `idasistencia` INT(11) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `cedula` VARCHAR(45) NULL DEFAULT NULL,
  `empleados` VARCHAR(45) NULL DEFAULT NULL,
  `horario_idhorario` INT(11) NULL DEFAULT NULL,
  `permiso_idpermiso` INT(11) NULL DEFAULT NULL,
  `horario_idhorario1` INT(11) NOT NULL,
  PRIMARY KEY (`idasistencia`),
  INDEX `fk_asistencia_horario1_idx` (`horario_idhorario1` ASC),
  CONSTRAINT `fk_asistencia_horario1`
    FOREIGN KEY (`horario_idhorario1`)
    REFERENCES `horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sanciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanciones` ;

CREATE TABLE IF NOT EXISTS `sanciones` (
  `idsanciones` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `fechaSancion` DATE NULL DEFAULT NULL,
  `empleado` VARCHAR(45) NULL DEFAULT NULL,
  `tipoSancion_idtipoSancion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idsanciones`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `atrazos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atrazos` ;

CREATE TABLE IF NOT EXISTS `atrazos` (
  `idatrazos` INT(11) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `horaEntrada2` TIME NULL DEFAULT NULL,
  `empleado` VARCHAR(45) NULL DEFAULT NULL,
  `horario_idhorario` INT(11) NULL DEFAULT NULL,
  `sanciones_idsanciones` INT(11) NULL DEFAULT NULL,
  `sanciones_idsanciones1` INT(11) NOT NULL,
  `horario_idhorario1` INT(11) NOT NULL,
  PRIMARY KEY (`idatrazos`),
  INDEX `fk_atrazos_sanciones1_idx` (`sanciones_idsanciones1` ASC),
  INDEX `fk_atrazos_horario1_idx` (`horario_idhorario1` ASC),
  CONSTRAINT `fk_atrazos_sanciones1`
    FOREIGN KEY (`sanciones_idsanciones1`)
    REFERENCES `sanciones` (`idsanciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atrazos_horario1`
    FOREIGN KEY (`horario_idhorario1`)
    REFERENCES `horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cruge_authitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cruge_authitem` ;

CREATE TABLE IF NOT EXISTS `cruge_authitem` (
  `name` VARCHAR(64) NOT NULL,
  `type` INT(11) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `bizrule` TEXT NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cruge_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cruge_user` ;

CREATE TABLE IF NOT EXISTS `cruge_user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `regdate` BIGINT(30) NULL DEFAULT NULL,
  `actdate` BIGINT(30) NULL DEFAULT NULL,
  `logondate` BIGINT(30) NULL DEFAULT NULL,
  `username` VARCHAR(64) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Hashed password',
  `authkey` VARCHAR(100) NULL DEFAULT NULL COMMENT 'llave de autentificacion',
  `state` INT(11) NULL DEFAULT '0',
  `totalsessioncounter` INT(11) NULL DEFAULT '0',
  `currentsessioncounter` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cruge_authassignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cruge_authassignment` ;

CREATE TABLE IF NOT EXISTS `cruge_authassignment` (
  `userid` INT(11) NOT NULL,
  `bizrule` TEXT NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `itemname` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`userid`, `itemname`),
  INDEX `fk_cruge_authassignment_cruge_authitem1` (`itemname` ASC),
  INDEX `fk_cruge_authassignment_user` (`userid` ASC),
  CONSTRAINT `fk_cruge_authassignment_cruge_authitem1`
    FOREIGN KEY (`itemname`)
    REFERENCES `cruge_authitem` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cruge_authassignment_user`
    FOREIGN KEY (`userid`)
    REFERENCES `cruge_user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cruge_authitemchild`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cruge_authitemchild` ;

CREATE TABLE IF NOT EXISTS `cruge_authitemchild` (
  `parent` VARCHAR(64) NOT NULL,
  `child` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC),
  CONSTRAINT `crugeauthitemchild_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `cruge_authitem` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `crugeauthitemchild_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `cruge_authitem` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cruge_field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cruge_field` ;

CREATE TABLE IF NOT EXISTS `cruge_field` (
  `idfield` INT(11) NOT NULL AUTO_INCREMENT,
  `fieldname` VARCHAR(20) NOT NULL,
  `longname` VARCHAR(50) NULL DEFAULT NULL,
  `position` INT(11) NULL DEFAULT '0',
  `required` INT(11) NULL DEFAULT '0',
  `fieldtype` INT(11) NULL DEFAULT '0',
  `fieldsize` INT(11) NULL DEFAULT '20',
  `maxlength` INT(11) NULL DEFAULT '45',
  `showinreports` INT(11) NULL DEFAULT '0',
  `useregexp` VARCHAR(512) NULL DEFAULT NULL,
  `useregexpmsg` VARCHAR(512) NULL DEFAULT NULL,
  `predetvalue` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idfield`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cruge_fieldvalue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cruge_fieldvalue` ;

CREATE TABLE IF NOT EXISTS `cruge_fieldvalue` (
  `idfieldvalue` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` INT(11) NOT NULL,
  `idfield` INT(11) NOT NULL,
  `value` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idfieldvalue`),
  INDEX `fk_cruge_fieldvalue_cruge_user1` (`iduser` ASC),
  INDEX `fk_cruge_fieldvalue_cruge_field1` (`idfield` ASC),
  CONSTRAINT `fk_cruge_fieldvalue_cruge_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `cruge_user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cruge_fieldvalue_cruge_field1`
    FOREIGN KEY (`idfield`)
    REFERENCES `cruge_field` (`idfield`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cruge_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cruge_session` ;

CREATE TABLE IF NOT EXISTS `cruge_session` (
  `idsession` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` INT(11) NOT NULL,
  `created` BIGINT(30) NULL DEFAULT NULL,
  `expire` BIGINT(30) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT '0',
  `ipaddress` VARCHAR(45) NULL DEFAULT NULL,
  `usagecount` INT(11) NULL DEFAULT '0',
  `lastusage` BIGINT(30) NULL DEFAULT NULL,
  `logoutdate` BIGINT(30) NULL DEFAULT NULL,
  `ipaddressout` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idsession`),
  INDEX `crugesession_iduser` (`iduser` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cruge_system`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cruge_system` ;

CREATE TABLE IF NOT EXISTS `cruge_system` (
  `idsystem` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `largename` VARCHAR(45) NULL DEFAULT NULL,
  `sessionmaxdurationmins` INT(11) NULL DEFAULT '30',
  `sessionmaxsameipconnections` INT(11) NULL DEFAULT '10',
  `sessionreusesessions` INT(11) NULL DEFAULT '1' COMMENT '1yes 0no',
  `sessionmaxsessionsperday` INT(11) NULL DEFAULT '-1',
  `sessionmaxsessionsperuser` INT(11) NULL DEFAULT '-1',
  `systemnonewsessions` INT(11) NULL DEFAULT '0' COMMENT '1yes 0no',
  `systemdown` INT(11) NULL DEFAULT '0',
  `registerusingcaptcha` INT(11) NULL DEFAULT '0',
  `registerusingterms` INT(11) NULL DEFAULT '0',
  `terms` BLOB NULL DEFAULT NULL,
  `registerusingactivation` INT(11) NULL DEFAULT '1',
  `defaultroleforregistration` VARCHAR(64) NULL DEFAULT NULL,
  `registerusingtermslabel` VARCHAR(100) NULL DEFAULT NULL,
  `registrationonlogin` INT(11) NULL DEFAULT '1',
  PRIMARY KEY (`idsystem`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleado` ;

CREATE TABLE IF NOT EXISTS `empleado` (
  `idempleado` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `fechaIngreso` TIME NULL DEFAULT NULL,
  `area` VARCHAR(45) NULL DEFAULT NULL,
  `foto` BLOB NULL DEFAULT NULL,
  `horario_idhorario` INT(11) NULL DEFAULT NULL,
  `horario_idhorario1` INT(11) NOT NULL,
  PRIMARY KEY (`idempleado`),
  INDEX `fk_empleado_horario1_idx` (`horario_idhorario1` ASC),
  CONSTRAINT `fk_empleado_horario1`
    FOREIGN KEY (`horario_idhorario1`)
    REFERENCES `horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permiso` ;

CREATE TABLE IF NOT EXISTS `permiso` (
  `idpermiso` INT(11) NOT NULL,
  `empleado` VARCHAR(45) NULL DEFAULT NULL,
  `fechaPermiso` DATE NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `asistencia_idasistencia` INT(11) NOT NULL,
  PRIMARY KEY (`idpermiso`),
  INDEX `fk_permiso_asistencia1_idx` (`asistencia_idasistencia` ASC),
  CONSTRAINT `fk_permiso_asistencia1`
    FOREIGN KEY (`asistencia_idasistencia`)
    REFERENCES `asistencia` (`idasistencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tiposancion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiposancion` ;

CREATE TABLE IF NOT EXISTS `tiposancion` (
  `idtipoSancion` INT(11) NOT NULL,
  `detalles` VARCHAR(45) NULL DEFAULT NULL,
  `sanciones_idsanciones` INT(11) NOT NULL,
  PRIMARY KEY (`idtipoSancion`),
  INDEX `fk_tiposancion_sanciones1_idx` (`sanciones_idsanciones` ASC),
  CONSTRAINT `fk_tiposancion_sanciones1`
    FOREIGN KEY (`sanciones_idsanciones`)
    REFERENCES `sanciones` (`idsanciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  `pass` VARCHAR(45) NULL DEFAULT NULL,
  `tipoUsuario` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vacaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vacaciones` ;

CREATE TABLE IF NOT EXISTS `vacaciones` (
  `idvacaciones` INT(11) NOT NULL,
  `fechaInicio` DATE NULL DEFAULT NULL,
  `fechaFin` DATE NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `empleado` VARCHAR(45) NULL DEFAULT NULL,
  `empleado_idempleado` INT(11) NOT NULL,
  PRIMARY KEY (`idvacaciones`),
  INDEX `fk_vacaciones_empleado1_idx` (`empleado_idempleado` ASC),
  CONSTRAINT `fk_vacaciones_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
