<?php

/**
 * This is the model base class for the table "asistencia".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Asistencia".
 *
 * Columns in table "asistencia" available as properties of the model,
 * followed by relations of table "asistencia" available as properties of the model.
 *
 * @property integer $idasistencia
 * @property string $fecha
 * @property string $cedula
 * @property string $empleados
 * @property integer $horario_idhorario
 * @property integer $permiso_idpermiso
 * @property integer $horario_idhorario1
 *
 * @property Horario $horarioIdhorario1
 * @property Permiso[] $permisos
 */
abstract class BaseAsistencia extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'asistencia';
    }

    public static function representingColumn() {
        return 'fecha';
    }

    public function rules() {
        return array(
            array('idasistencia, horario_idhorario1', 'required'),
            array('idasistencia, horario_idhorario, permiso_idpermiso, horario_idhorario1', 'numerical', 'integerOnly'=>true),
            array('cedula, empleados', 'length', 'max'=>45),
            array('fecha', 'safe'),
            array('fecha, cedula, empleados, horario_idhorario, permiso_idpermiso', 'default', 'setOnEmpty' => true, 'value' => null),
            array('idasistencia, fecha, cedula, empleados, horario_idhorario, permiso_idpermiso, horario_idhorario1', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'horarioIdhorario1' => array(self::BELONGS_TO, 'Horario', 'horario_idhorario1'),
            'permisos' => array(self::HAS_MANY, 'Permiso', 'asistencia_idasistencia'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'idasistencia' => Yii::t('app', 'Idasistencia'),
                'fecha' => Yii::t('app', 'Fecha'),
                'cedula' => Yii::t('app', 'Cedula'),
                'empleados' => Yii::t('app', 'Empleados'),
                'horario_idhorario' => Yii::t('app', 'Horario Idhorario'),
                'permiso_idpermiso' => Yii::t('app', 'Permiso Idpermiso'),
                'horario_idhorario1' => Yii::t('app', 'Horario Idhorario1'),
                'horarioIdhorario1' => null,
                'permisos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('idasistencia', $this->idasistencia);
        $criteria->compare('fecha', $this->fecha, true);
        $criteria->compare('cedula', $this->cedula, true);
        $criteria->compare('empleados', $this->empleados, true);
        $criteria->compare('horario_idhorario', $this->horario_idhorario);
        $criteria->compare('permiso_idpermiso', $this->permiso_idpermiso);
        $criteria->compare('horario_idhorario1', $this->horario_idhorario1);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}