<?php

/**
 * This is the model base class for the table "atrazos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Atrazos".
 *
 * Columns in table "atrazos" available as properties of the model,
 * followed by relations of table "atrazos" available as properties of the model.
 *
 * @property integer $idatrazos
 * @property string $fecha
 * @property string $horaEntrada2
 * @property string $empleado
 * @property integer $horario_idhorario
 * @property integer $sanciones_idsanciones
 * @property integer $sanciones_idsanciones1
 * @property integer $horario_idhorario1
 *
 * @property Sanciones $sancionesIdsanciones1
 * @property Horario $horarioIdhorario1
 */
abstract class BaseAtrazos extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'atrazos';
    }

    public static function representingColumn() {
        return 'fecha';
    }

    public function rules() {
        return array(
            array('idatrazos, sanciones_idsanciones1, horario_idhorario1', 'required'),
            array('idatrazos, horario_idhorario, sanciones_idsanciones, sanciones_idsanciones1, horario_idhorario1', 'numerical', 'integerOnly'=>true),
            array('empleado', 'length', 'max'=>45),
            array('fecha, horaEntrada2', 'safe'),
            array('fecha, horaEntrada2, empleado, horario_idhorario, sanciones_idsanciones', 'default', 'setOnEmpty' => true, 'value' => null),
            array('idatrazos, fecha, horaEntrada2, empleado, horario_idhorario, sanciones_idsanciones, sanciones_idsanciones1, horario_idhorario1', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'sancionesIdsanciones1' => array(self::BELONGS_TO, 'Sanciones', 'sanciones_idsanciones1'),
            'horarioIdhorario1' => array(self::BELONGS_TO, 'Horario', 'horario_idhorario1'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'idatrazos' => Yii::t('app', 'Idatrazos'),
                'fecha' => Yii::t('app', 'Fecha'),
                'horaEntrada2' => Yii::t('app', 'Hora Entrada2'),
                'empleado' => Yii::t('app', 'Empleado'),
                'horario_idhorario' => Yii::t('app', 'Horario Idhorario'),
                'sanciones_idsanciones' => Yii::t('app', 'Sanciones Idsanciones'),
                'sanciones_idsanciones1' => Yii::t('app', 'Sanciones Idsanciones1'),
                'horario_idhorario1' => Yii::t('app', 'Horario Idhorario1'),
                'sancionesIdsanciones1' => null,
                'horarioIdhorario1' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('idatrazos', $this->idatrazos);
        $criteria->compare('fecha', $this->fecha, true);
        $criteria->compare('horaEntrada2', $this->horaEntrada2, true);
        $criteria->compare('empleado', $this->empleado, true);
        $criteria->compare('horario_idhorario', $this->horario_idhorario);
        $criteria->compare('sanciones_idsanciones', $this->sanciones_idsanciones);
        $criteria->compare('sanciones_idsanciones1', $this->sanciones_idsanciones1);
        $criteria->compare('horario_idhorario1', $this->horario_idhorario1);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}