<?php

/**
 * This is the model base class for the table "sanciones".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sanciones".
 *
 * Columns in table "sanciones" available as properties of the model,
 * followed by relations of table "sanciones" available as properties of the model.
 *
 * @property integer $idsanciones
 * @property string $descripcion
 * @property string $fechaSancion
 * @property string $empleado
 * @property integer $tipoSancion_idtipoSancion
 *
 * @property Atrazos[] $atrazoses
 * @property Tiposancion[] $tiposancions
 */
abstract class BaseSanciones extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'sanciones';
    }

    public static function representingColumn() {
        return 'descripcion';
    }

    public function rules() {
        return array(
            array('idsanciones', 'required'),
            array('idsanciones, tipoSancion_idtipoSancion', 'numerical', 'integerOnly'=>true),
            array('descripcion, empleado', 'length', 'max'=>45),
            array('fechaSancion', 'safe'),
            array('descripcion, fechaSancion, empleado, tipoSancion_idtipoSancion', 'default', 'setOnEmpty' => true, 'value' => null),
            array('idsanciones, descripcion, fechaSancion, empleado, tipoSancion_idtipoSancion', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'atrazoses' => array(self::HAS_MANY, 'Atrazos', 'sanciones_idsanciones1'),
            'tiposancions' => array(self::HAS_MANY, 'Tiposancion', 'sanciones_idsanciones'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'idsanciones' => Yii::t('app', 'Idsanciones'),
                'descripcion' => Yii::t('app', 'Descripcion'),
                'fechaSancion' => Yii::t('app', 'Fecha Sancion'),
                'empleado' => Yii::t('app', 'Empleado'),
                'tipoSancion_idtipoSancion' => Yii::t('app', 'Tipo Sancion Idtipo Sancion'),
                'atrazoses' => null,
                'tiposancions' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('idsanciones', $this->idsanciones);
        $criteria->compare('descripcion', $this->descripcion, true);
        $criteria->compare('fechaSancion', $this->fechaSancion, true);
        $criteria->compare('empleado', $this->empleado, true);
        $criteria->compare('tipoSancion_idtipoSancion', $this->tipoSancion_idtipoSancion);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}