<?php

/**
 * This is the model base class for the table "usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuario".
 *
 * Columns in table "usuario" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idusuario
 * @property string $nombre
 * @property string $apellido
 * @property string $usuario
 * @property string $pass
 * @property string $tipoUsuario
 *
 */
abstract class BaseUsuario extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'usuario';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('idusuario', 'required'),
            array('idusuario', 'numerical', 'integerOnly'=>true),
            array('nombre, apellido, usuario, pass, tipoUsuario', 'length', 'max'=>45),
            array('nombre, apellido, usuario, pass, tipoUsuario', 'default', 'setOnEmpty' => true, 'value' => null),
            array('idusuario, nombre, apellido, usuario, pass, tipoUsuario', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'idusuario' => Yii::t('app', 'Idusuario'),
                'nombre' => Yii::t('app', 'Nombre'),
                'apellido' => Yii::t('app', 'Apellido'),
                'usuario' => Yii::t('app', 'Usuario'),
                'pass' => Yii::t('app', 'Pass'),
                'tipoUsuario' => Yii::t('app', 'Tipo Usuario'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('idusuario', $this->idusuario);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('apellido', $this->apellido, true);
        $criteria->compare('usuario', $this->usuario, true);
        $criteria->compare('pass', $this->pass, true);
        $criteria->compare('tipoUsuario', $this->tipoUsuario, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}