<?php

/**
 * This is the model base class for the table "tiposancion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tiposancion".
 *
 * Columns in table "tiposancion" available as properties of the model,
 * followed by relations of table "tiposancion" available as properties of the model.
 *
 * @property integer $idtipoSancion
 * @property string $detalles
 * @property integer $sanciones_idsanciones
 *
 * @property Sanciones $sancionesIdsanciones
 */
abstract class BaseTiposancion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tiposancion';
    }

    public static function representingColumn() {
        return 'detalles';
    }

    public function rules() {
        return array(
            array('idtipoSancion, sanciones_idsanciones', 'required'),
            array('idtipoSancion, sanciones_idsanciones', 'numerical', 'integerOnly'=>true),
            array('detalles', 'length', 'max'=>45),
            array('detalles', 'default', 'setOnEmpty' => true, 'value' => null),
            array('idtipoSancion, detalles, sanciones_idsanciones', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'sancionesIdsanciones' => array(self::BELONGS_TO, 'Sanciones', 'sanciones_idsanciones'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'idtipoSancion' => Yii::t('app', 'Idtipo Sancion'),
                'detalles' => Yii::t('app', 'Detalles'),
                'sanciones_idsanciones' => Yii::t('app', 'Sanciones Idsanciones'),
                'sancionesIdsanciones' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('idtipoSancion', $this->idtipoSancion);
        $criteria->compare('detalles', $this->detalles, true);
        $criteria->compare('sanciones_idsanciones', $this->sanciones_idsanciones);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}